version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportify
      MYSQL_USER: su
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - sportify-network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportify-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - sportify-network

networks:
  sportify-network:
    driver: bridge

volumes:
  mysql_data: