version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportify
      MYSQL_USER: su
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sportify-network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportify-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sportify-network

networks:
  sportify-network:
    driver: bridge

volumes:
  mysql_data: